name: ESLint Gate

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
            node-version: '20'

      - name: Install ESLint
        run: |
          npm install eslint eslint-plugin-react eslint-plugin-react-hooks eslint-plugin-react-refresh

      - name: Run ESLint
        run: |
          npm run lint
