name: Prettier Style Gate

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Prettier Action
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: --check **/*.{js,scss,css,json}
